### ISSUE TITLE
I and Q bit-stream synchronization

### ISSUE THREAD

**Issue by elektronika-ba** [ZipCPU/sdr#2]
Hi,

How is the synchronization of I and Q bit-streams done? Reading through the datasheet I don't see any way of doing that.

Is it assumed that after configuring the SX1257 into RX or TX mode, the bit-stream starts and that is the synchronization?

Also, what is the format of I and Q values after receiving? - Is it the middle value 255/2 = no signal value?

Thanks

**Comment by ZipCPU** [comment]
> How is the synchronization of I and Q bit-streams done? Reading through the datasheet I don't see any way of doing that.

On transmit, there's a clock.  On RX the bit streams are just way over sampled in the first place.  You could use the clock, I didn't.

> Also, what is the format of I and Q values after receiving? - Is it the middle value 255/2 = no signal value?

I&Q values are just +/- 1.  It's not a very capable receiver.

Dan

**Comment by elektronika-ba** [comment]
I was trying to relate this to RTL-SDR and how we are getting IQ samples from them. I know that we are getting samples as 8 bits for "I" and 8 bits for "Q" where value of 0xFF/2 corresponds to "no RF signal value".

From the SX1257 (and SX1255) datasheet the IQ samples are just getting dumped out like crazy, without beginning or end. Then I opened my eyes and saw that this is an output from 1-bit sigma delta, meaning that we don't have data at this stage which is packed or organized in some form for processing, like we get them from RTL-SDR devices.

My assumption was wrong and I need to go back to the drawing board regarding my project with SX125x.

Looks like I need to look at your code even further, but now with a different mindset.

Update: Is there an implementation in your code that would calculate, for example, RSSI of the received signal? I know how to do this for an IQ sample, but talking about the SX125x there is no "sample", there is a "stream".

**Comment by ZipCPU** [comment]
> Is there an implementation in your code that would calculate, for example, RSSI of the received signal?

No, there is no RSSI indicator.  A nearby histogram is available if necessary  for something like that if necessary.

Dan
